name: Deploy to Code Engine

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Code Engine
        uses: ibm/code-engine-github-action@v1
        with:
          api-key: ${{ secrets.IBM_IAM_API_KEY }}
          resource-group: 'Default'
          region: 'us-east'
          project: 'code-engine-inco'
          component: 'app'
          name: 'test-ce-deploy'
          build-source: './'
          cpu: 0.25
          memory: 1G